# Generated by Django 3.0.6 on 2020-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('location', models.CharField(max_length=35)),
                ('ceo', models.CharField(max_length=35)),
            ],
        ),
    ]
