# Generated by Django 3.0.6 on 2020-07-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contactinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='contactinfo_ptr',
        ),
        migrations.DeleteModel(
            name='Contactinfo',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
