# Generated by Django 3.0.6 on 2020-07-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0003_student_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
