# Generated by Django 3.0.6 on 2020-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0006_auto_20200712_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
